#!/bin/bash

osch=0
echo "1. Unix (SunOS)"
echo "2. Linux (Red Hat)"
echo -n "Select your os choice [1 or 2]? "
read osch
if [ $osch -eq 1 ] ; then
     echo "You chose Unix (SunOS)"
else
    if [ $osch -eq 2 ] ; then
      echo "You chose Linux (Red Hat)"
    fi
fi
